#:import random random
<window>:
    orientation:'vertical'
    BoxLayout:
        TextInput:
            id:txt
            text:'write something'
            font_size:'50'
            on_text:lbl.color=[random.random() for i in range(3)]+[1]
        Scatter:
            Label:
                id:lbl
                text: txt.text
                font_size:50
    FloatLayout:
        Label:
            text:'try writting \nsomething in the textinput'
            font_size:50
    
            